# Generated by Django 3.1.5 on 2021-05-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='zip_file',
            field=models.FileField(upload_to='static/zips/'),
        ),
    ]
