# Generated by Django 3.1.5 on 2021-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_file_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='time',
            field=models.CharField(default='Fri May 14 16:41:07 2021', max_length=40),
        ),
    ]
