# Generated by Django 3.1.5 on 2021-05-14 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_auto_20210514_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default='Fri May 14 16:42:35 2021', max_length=40),
        ),
    ]
