# Generated by Django 3.1.5 on 2021-05-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20210514_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='text',
            field=models.CharField(default='No Name', max_length=20),
        ),
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default='Fri May 14 17:28:50 2021', max_length=40),
        ),
    ]
