# Generated by Django 3.1.5 on 2021-05-15 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20210515_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='time',
            field=models.CharField(default='Sat May 15 01:36:26 2021', max_length=40),
        ),
    ]
